# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bba6cde7ff14cbbbc0fe6dd345d5183f3acbd570ab2afd899dd37b7399d363cd4ee3d433100d9f31db7180b7e4ef241da51f0e794b639700e1e50d28c5adcc84

test:
  secret_key_base: 336491e59b933bfa962f31773df5e779ace96b962cc2e08e440862d1e9288f9b0b63a3763d8fe401f42db8256244f19f2273319ae4a45941d4a7368a78c1342b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
